First draft of PIE-hosted Conjur demo

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,79 +1,71 @@
 #!/bin/bash -e
-BIN_DIR=$(cd "$(dirname $0)/."  && pwd)
-ROOT_DIR=$BIN_DIR/../
+API_KEY=$1
+ACCOUNT=$2
 APP_NAME="hello-world"
+
+if [[ -z "$API_KEY" || -z "$ACCOUNT" ]]
+  then
+    echo "Missing required argument"
+    echo "Correct usage: ./bin/start CONJUR_ACCOUNT CONJUR_API_KEY"
+    exit 1
+fi
+
 
 # stop will make sure PCFDev is running and the `cf` binary is installed
 ./bin/stop
 
-docker-compose up -d conjur pg
+# get a Conjur CLI container running and load the root policy
+docker pull conjurinc/cli5
+docker run -d -it -v $PWD:/work -w /work \
+  -e CONJUR_AUTHN_API_KEY="$API_KEY" \
+  -e CONJUR_AUTHN_LOGIN="admin" \
+  -e CONJUR_ACCOUNT="$ACCOUNT" \
+  -e CONJUR_APPLIANCE_URL="eval.conjur.org" \
+  --entrypoint bash conjurinc/cli5 -c '
+    cat policy/root.yml | sed -e "$replace" | conjur policy load --replace root -;
+    conjur variable values add app/database/username "a database username";
+    conjur variable values add app/database/password "a database password";
+    conjur variable values add app/stripe/private_key "a stripe private_key"
+  '
 
+echo "-------------------------------------------"
+echo "CONJUR POLICY LOAD"
+echo "Setting db username to 'a database username'"
+echo "Setting db password to 'a database password'"
+echo "Setting stripe private key to 'a stripe private_key'"
+echo "-------------------------------------------"
+
+# create a space for the demo app
 cf create-space demo
 cf target -s demo
 
-rm -rf meta-buildpack
-git clone https://github.com/cf-platform-eng/meta-buildpack.git
-pushd meta-buildpack
-  ./build
-  ./upload
-popd
-rm -rf meta-buildpack
+# create the Conjur service
+cf create-service cyberark-conjur community conjur
 
-pushd cloudfoundry-conjur-buildpack
-  ./upload.sh
-popd
-
-pushd conjur-service-broker
-  cf push --no-start --random-route
-
-  printf "Waiting for API key... "
-  while [[ ! -f $ROOT_DIR/tmp/api_key ]]
-  do
-    sleep 1
-  done
-
-  while [[ -z `cat $ROOT_DIR/tmp/api_key` ]]
-  do
-    sleep 1
-  done
-  echo "Done."
-
-  cf set-env conjur-service-broker SECURITY_USER_NAME TEMPORARY
-  cf set-env conjur-service-broker SECURITY_USER_PASSWORD TEMPORARY
-  cf set-env conjur-service-broker CONJUR_ACCOUNT default
-  cf set-env conjur-service-broker CONJUR_APPLIANCE_URL http://host.pcfdev.io:3000
-  cf set-env conjur-service-broker CONJUR_AUTHN_LOGIN admin
-  cf set-env conjur-service-broker CONJUR_AUTHN_API_KEY "$(cat $ROOT_DIR/tmp/api_key)"
-
-  cf start conjur-service-broker
-
-  APP_URL="http://`cf app conjur-service-broker | grep -E -w 'urls:|routes:' | awk '{print $2}'`"
-  cf create-service-broker conjur-service-broker "TEMPORARY" "TEMPORARY" $APP_URL --space-scoped
-
-  printf "Waiting for Conjur to be ready... "
-  while [[ ! $(curl -o /dev/null -s -w '%{http_code}\n' localhost:3000) == 200 ]]
-  do
-    echo "."
-    sleep 1
-  done
-  echo "Done."
-
-  cf create-service cyberark-conjur community conjur
-popd
-
+# push the app without starting it
 pushd app
   cf push --no-start
 popd
 
-# run policy
+# load the base policy
 APP_HOST_NAME=$(cf env $APP_NAME | grep authn_login | awk '{print $NF}' | sed 's/host\///g; s/"//g')
-docker-compose run --rm -e CONJUR_AUTHN_API_KEY="$(cat $ROOT_DIR/tmp/api_key)" --entrypoint bash client -c "
-cat /policy/root.yml | sed -e 's/<APP_HOST_NAME>/${APP_HOST_NAME}/' | conjur policy load root -
-conjur variable values add app/database/username 'a database username'
-conjur variable values add app/database/password 'a database password'
-conjur variable values add app/stripe/private_key 'a stripe private_key'
-"
+
+echo "Host GUID: $APP_HOST_NAME"
+
+# add an entitlement for the new host
+docker run -d -it -v $PWD:/work -w /work \
+  -e CONJUR_AUTHN_API_KEY="$API_KEY" \
+  -e APP_HOST_NAME="$APP_HOST_NAME" \
+  -e CONJUR_AUTHN_LOGIN="admin" \
+  -e CONJUR_ACCOUNT="$ACCOUNT" \
+  -e CONJUR_APPLIANCE_URL="eval.conjur.org" \
+  --entrypoint bash conjurinc/cli5 -c '
+    replace="s/<APP_HOST_NAME>/$APP_HOST_NAME/";
+    cat policy/entitlements.yml | sed -e "$replace" | conjur policy load root -
+  '
 
 pushd app
   cf start $APP_NAME
 popd
+
+echo "App was deployed to $(cf app hello-world | grep routes | awk '{print $NF}')"
